module: src.client.agents.VLLMAgent
parameters:
  url: http://localhost:9876/v1/chat/completions
  headers:
    Content-Type: application/json
    Authorization: EMPTY
  model: "Qwen/QwQ-32B"
  body:
    temperature: 0
    max_tokens: 1024
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
